// frontend/src/components/Sidebar.tsx
import React from 'react'

type SidebarProps = {
  activeSection: string
  onSelect: (section: string) => void
}

const items = [
  { key: 'chat', label: '聊天历史' },
  { key: 'knowledge', label: '知识库' },
  { key: 'agents', label: 'Agent 管理' },
  { key: 'settings', label: '设置' }
]

export default function Sidebar({ activeSection, onSelect }: SidebarProps) {
  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center text-black font-bold">OF</div>
        <div>
          <div className="text-white font-semibold">OmniForge</div>
          <div className="text-muted text-sm">Developer AI Workspace</div>
        </div>
      </div>

      <nav className="mt-6">
        <ul className="space-y-2 text-sm">
          {items.map(item => (
            <li key={item.key}>
              <button
                type="button"
                onClick={() => onSelect(item.key)}
                className={`w-full text-left p-2 rounded-lg transition ${
                  activeSection === item.key
                    ? 'bg-primary text-black'
                    : 'hover:bg-hover text-text'
                }`}
              >
                {item.label}
              </button>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  )
}

// frontend/src/components/layout/Sidebar.vue
<template>
  <aside
    class="w-[300px] flex-shrink-0 h-full flex flex-col bg-sidebar-bg border-r border-border select-none"
  >
    <!-- Logo -->
    <div class="px-5 pt-5 pb-4">
      <div class="flex items-center gap-3">
        <div
          class="w-8 h-8 rounded-lg bg-primary flex items-center justify-center text-white font-bold text-sm"
        >
          OF
        </div>
        <span class="text-base font-semibold text-text">OmniForge</span>
      </div>
    </div>

    <!-- Segmented Control -->
    <SegmentedControl />

    <!-- Nav items -->
    <nav class="px-3 mt-3 space-y-0.5">
      <NavItem
        v-for="item in navItems"
        :key="item.label"
        :icon="item.icon"
        :label="item.label"
        :active="item.active"
        @click="item.action?.()"
      />
    </nav>

    <!-- Recent Chats -->
    <ChatHistory />

    <!-- Spacer -->
    <div class="flex-1 min-h-0" />

    <!-- User Profile -->
    <UserProfile />
  </aside>
</template>

<script setup lang="ts">
import { computed, inject } from 'vue'
import { Plus, Folder, BookOpen, Wrench, Settings } from 'lucide-vue-next'
import SegmentedControl from '@/components/sidebar/SegmentedControl.vue'
import NavItem from '@/components/sidebar/NavItem.vue'
import ChatHistory from '@/components/sidebar/ChatHistory.vue'
import UserProfile from '@/components/sidebar/UserProfile.vue'
import type { ChatState } from '@/composables/useChatState'

const chatState = inject<ChatState>('chatState')!

const navItems = computed(() => [
  { icon: Plus, label: '新对话', active: chatState.activeSection.value === 'chat', action: () => { chatState.newChat(); chatState.activeSection.value = 'chat' } },
  { icon: Folder, label: '项目', active: chatState.activeSection.value === 'projects', action: () => { chatState.activeSection.value = 'projects' } },
  { icon: BookOpen, label: '知识库', active: chatState.activeSection.value === 'knowledge', action: () => { chatState.activeSection.value = 'knowledge' } },
  { icon: Wrench, label: '工具', active: false, action: undefined },
  { icon: Settings, label: '设置', active: chatState.activeSection.value === 'settings', action: () => { chatState.activeSection.value = 'settings' } },
])
</script>
